---
# Per environment values which override defaults in hmpps-esupervision-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: esupervision-api-preprod.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/limit-rps: "50"
      nginx.ingress.kubernetes.io/limit-rpm: "800"
      nginx.ingress.kubernetes.io/limit-burst: "120"

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    HOSTED_AT: "https://esupervision-preprod.hmpps.service.justice.gov.uk"
    API_BASE_URL: "https://esupervision-api-preprod.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk/"
    MPOP_URL: "https://manage-people-on-probation-preprod.hmpps.service.justice.gov.uk"
    POP_UI_URL: "https://probation-check-in-preprod.hmpps.service.justice.gov.uk"
    NDILIUS_API_URL: "https://esupervision-and-delius-preprod.hmpps.service.justice.gov.uk"
    APP_SCHEDULING_CHECKIN_NOTIFICATION_ENABLED: "false"
    APP_SCHEDULING_CHECKIN_NOTIFICATION_CRON: "-"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_esupervision_alerts_nonprod
