---
# Per environment values which override defaults in hmpps-esupervision-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: esupervision-api-dev.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/limit-rps: "20"
      nginx.ingress.kubernetes.io/limit-rpm: "500"
      nginx.ingress.kubernetes.io/limit-burst: "50"

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HOSTED_AT: "https://esupervision-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL: "https://esupervision-api-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API: "https://manage-users-api-dev.hmpps.service.justice.gov.uk/"
    MPOP_URL: "https://manage-people-on-probation-dev.hmpps.service.justice.gov.uk"
    POP_UI_URL: "https://probation-check-in-dev.hmpps.service.justice.gov.uk"
    APP_SCHEDULING_CHECKIN_NOTIFICATION_ENABLED: "false"
    APP_SCHEDULING_CHECKIN_NOTIFICATION_CRON: "-"
    APP_SCHEDULING_OFFENDER_CHECKIN_EXPIRY_CRON: "0 15 9,12,13,15,16 * * *"
    APP_SCHEDULING_CHECKIN_REMINDER_NOTIFICATION_CRON: "0 15 9,15,16 * * *"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_esupervision_alerts_nonprod

app:
  scheduling:
    v2-checkin-expiry:
      cron: "0 15 9,15,16 * * *"