---
# Per environment values which override defaults in hmpps-esupervision-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: esupervision-api-dev.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/limit-rps: "2"
      nginx.ingress.kubernetes.io/limit-rpm: "15"
      # nginx.ingress.kubernetes.io/limit-burst: "20"

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HOSTED_AT: "https://esupervision-dev.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API: "https://manage-users-api-dev.hmpps.service.justice.gov.uk/"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_esupervision_alerts_nonprod
