---
# Per environment values which override defaults in hmpps-esupervision-api/values.yaml

generic-service:
  ingress:
    host: esupervision-api.hmpps.service.justice.gov.uk
    annotations:
      nginx.ingress.kubernetes.io/limit-rps: "50"
      nginx.ingress.kubernetes.io/limit-rpm: "800"
      nginx.ingress.kubernetes.io/limit-burst: "120"

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    HOSTED_AT: "https://esupervision.hmpps.service.justice.gov.uk"
    API_BASE_URL: "https://esupervision-api.hmpps.service.justice.gov.uk"
    MANAGE_USERS_API: "https://manage-users-api.hmpps.service.justice.gov.uk/"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_esupervision_alerts_prod
